import{a as m}from"./assets/vendor-B2YOV0tR.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))n(s);new MutationObserver(s=>{for(const o of s)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function r(s){const o={};return s.integrity&&(o.integrity=s.integrity),s.referrerPolicy&&(o.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?o.credentials="include":s.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(s){if(s.ep)return;s.ep=!0;const o=r(s);fetch(s.href,o)}})();async function L(e=1,t=8){const r=`https://sound-wave.b.goit.study/api/artists?page=${e}&limit=${t}`;try{const{data:n}=await m.get(r);return n}catch(n){return console.error("Помилка отримання артистів:",n),null}}function y(e){if(!e||!e.strArtistThumb||!e.strArtist||!e.genres||!e.strBiographyEN)return"";const t=e.strBiographyEN.length>200?e.strBiographyEN.slice(0,200)+"...":e.strBiographyEN;return`
        <li class="artist-card">
            <img src="${e.strArtistThumb}" alt="${e.strArtist}" class="artist-image" data-id="${e._id}" />
            <h3 class="artist-name">${e.strArtist}</h3>
            <p class="artist-genre">${e.genres.join(", ")}</p>
            <p class="artist-bio" data-full="${e.strBiographyEN}">${t}</p>
            <button class="learn-more">Learn More</button>
        </li>
    `}m.create({baseURL:"https://sound-wave.b.goit.study/api"});const u=document.querySelector(".burger-icon"),d=document.querySelector(".burger-icon-x"),i=document.querySelector(".header-nav-list"),l=document.body;document.querySelector(".burger-svg");u.addEventListener("click",f);d.addEventListener("click",f);i.addEventListener("click",e=>{e.target.nodeName==="A"&&(i.classList.remove("active"),d.classList.remove("active"),u.classList.remove("active"),l.classList.remove("lock"))});function f(){i.classList.toggle("active"),u.classList.toggle("active"),d.classList.toggle("active"),i.classList.contains("active")?l.classList.add("lock"):l.classList.remove("lock")}const g=document.querySelector(".list-cards"),h=document.getElementById("load-more");let a=1;const v=8;async function p(e=1,t=8){try{const r=await L(e,t);if(!r||!r.artists||!Array.isArray(r.artists))throw new Error("Невірний формат даних: artists відсутній або не є масивом");console.log(`Отримані артисти для сторінки ${e}:`,r.artists),b(r.artists)}catch(r){console.error("Помилка при завантаженні артистів:",r.message)}}function b(e){g.innerHTML="";const t=e.map(y).join("");g.insertAdjacentHTML("beforeend",t)}h.addEventListener("click",()=>{a++,console.log(`Завантажуємо сторінку: ${a}`),p(a,v)});document.addEventListener("click",e=>{if(e.target.classList.contains("learn-more")){const t=e.target.previousElementSibling,r=t.dataset.full;if(!r)return;t.classList.contains("expanded")?(t.innerHTML=r.slice(0,200)+"...",e.target.textContent="Learn More"):(t.innerHTML=r,e.target.textContent="Show Less"),t.classList.toggle("expanded")}});p();
//# sourceMappingURL=index.js.map
