import{a as v,S as b}from"./assets/vendor-DtrLoC2-.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();const w=v.create({baseURL:"https://sound-wave.b.goit.study/api"});async function S(){try{return await w.get("/feedbacks")}catch(e){throw console.error("Помилка при отриманні відгуків:",e),e}}const u=document.querySelector(".burger-icon"),p=document.querySelector(".burger-icon-x"),c=document.querySelector(".header-nav-list"),d=document.body;document.querySelector(".burger-svg");u.addEventListener("click",y);p.addEventListener("click",y);c.addEventListener("click",e=>{e.target.nodeName==="A"&&(c.classList.remove("active"),p.classList.remove("active"),u.classList.remove("active"),d.classList.remove("lock"))});function y(){c.classList.toggle("active"),u.classList.toggle("active"),p.classList.toggle("active"),c.classList.contains("active")?d.classList.add("lock"):d.classList.remove("lock")}async function E(e=1,t=8){const s=`https://sound-wave.b.goit.study/api/artists?page=${e}&limit=${t}`;try{const{data:n}=await v.get(s);return n}catch(n){return console.error("Помилка отримання артистів:",n),null}}function A(e){if(!e||!e.strArtistThumb||!e.strArtist||!e.genres||!e.strBiographyEN)return"";const t=e.strBiographyEN.length>200?e.strBiographyEN.slice(0,200)+"...":e.strBiographyEN;return`
        <li class="artist-card">
            <img src="${e.strArtistThumb}" alt="${e.strArtist}" class="artist-image" data-id="${e._id}" />
            <h3 class="artist-name">${e.strArtist}</h3>
            <p class="artist-genre">${e.genres.join(", ")}</p>
            <p class="artist-bio" data-full="${e.strBiographyEN}">${t}</p>
            <button class="learn-more">Learn More</button>
        </li>
    `}const $=document.querySelector(".swiper-wrapper");function k(e){const t=Math.round(e);let s="";for(let n=0;n<5;n++)n<t?s+='<span class="star-icon filled"> ★ </span>':s+='<span class="star-icon empty"> ★ </span>';return s}async function x(){const n=(await S()).data.data.map(r=>{let o=r.rating;return`
 <div class="swiper-slide">
<div class="feedback-card">
<div class="feedback-rating-display"> ${k(o)} </div>
 <p class="feedback-text">"${r.descr}"</p>
 <p class="feedback-author">${r.name}</p>
 </div>
</div>
`}).join("");$.innerHTML=n,i.update()}const i=new b(".swiper",{initialSlide:0,navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"}});x();const f=document.querySelector(".dot.first"),g=document.querySelector(".dot.current"),m=document.querySelector(".dot.last");i.on("slideChange",()=>{const e=i.realIndex,t=i.slides.length-i.loopedSlides*2;f.classList.remove("active"),g.classList.remove("active"),m.classList.remove("active"),e===0?f.classList.add("active"):e===t-1?m.classList.add("active"):g.classList.add("active")});const L=document.querySelector(".list-cards"),B=document.getElementById("load-more");let l=1;const M=8;async function h(e=1,t=8){try{const s=await E(e,t);if(!s||!s.artists||!Array.isArray(s.artists))throw new Error("Невірний формат даних: artists відсутній або не є масивом");console.log(`Отримані артисти для сторінки ${e}:`,s.artists),q(s.artists)}catch(s){console.error("Помилка при завантаженні артистів:",s.message)}}function q(e){L.innerHTML="";const t=e.map(A).join("");L.insertAdjacentHTML("beforeend",t)}B.addEventListener("click",()=>{l++,console.log(`Завантажуємо сторінку: ${l}`),h(l,M)});document.addEventListener("click",e=>{if(e.target.classList.contains("learn-more")){const t=e.target.previousElementSibling,s=t.dataset.full;if(!s)return;t.classList.contains("expanded")?(t.innerHTML=s.slice(0,200)+"...",e.target.textContent="Learn More"):(t.innerHTML=s,e.target.textContent="Show Less"),t.classList.toggle("expanded")}});h();
//# sourceMappingURL=index.js.map
